List<String> driving = [
  "May an officer search me?",
  "The police may not search you if you are not under arrest or if they lack a valid warrant. If you don’t consent to an unwarranted search and they do it anyway, anything they find—even if it’s incriminating—may be dismissed. The right to be free from a warrantless search and seizure is protected by the Fourth Amendment to the Constitution.",
  "That said, the police may pat you down through your clothing (without a warrant or arrest) if they have reasonable suspicion that you’re carrying a weapon. This is one of those gray areas of law enforcement and has been a source of controversy and tension in many communities, since the rationale for a pat down typically comes down to the officer’s word versus that of the individual who was patted down.",
  "May I record the police during an interaction?",
  "You have the right to take images (video and still pictures) in a public place in all states, including actions by law enforcement, as long as you don’t interfere with their duties. Also, individuals consent to having their image taken by virtue of being in a public place (such as parks, streets, public sidewalks, and while participating in protests). This means you also have the right to record police interactions that don’t involve you personally, as long as you don’t interfere.",
  "Law enforcement officers may not require you to delete your videos and pictures or demand that you relinquish your phone or camera without a valid warrant. That said, while recording images is a federally protected right, the recording of sound without the subjects’ consent varies by state.",
  "Regardless, the police may try to take your recording device or get you to delete images. If they request your recording device or tell you to stop recording, inform them of your rights. They may back off once they realize you know your rights. But if this request becomes a demand or otherwise intensifies, your best option may be to comply (in order to avoid further escalation) and then file a police misconduct claim later.",
  "What are my rights if I’m pulled over by the police?",
  "If you are pulled over by the police while driving your car, it is important that you stay calm. Pull over as quickly as it is safe to do so, making sure you’re not obstructing traffic, and turn off your engine. Turn on the internal light, open the window part way, and place your hands on the wheel if you’re the driver. Passengers should also keep their hands visible.",
  "Since the police are prepared to respond at a moment’s notice if they fear they are in danger, it’s important to remain calm and avoid making any sudden movements. Keep your hands where the officer can see them and provide any necessary documents upon request, but wait until they ask for these documents. Reaching into your pocket or glove compartment unannounced could cause an escalation.",
  "Make sure to memorize or write down badge or patrol car numbers and obtain witness contact information if you believe that your rights have been violated. Capturing video to do so is within your rights. While the legal doctrine of “qualified immunity”—the requirement that officers may only be held liable for actions that violate “clearly established” federal law—makes it very difficult for civilians to prevail in lawsuits against the police, don’t let that stop you from reporting any misconduct that you experience.",
  "Do police have to tell you why they pulled you over before asking for ID?",
  "Generally speaking, no. Police do not have to tell you why they are stopping you before asking for ID in a traffic stop, though it may be a standard practice in many areas. The officer must have a reason—i.e., probable cause—for the stop, but they are not legally required to tell you. That said, if taken to court, the police offer must provide their reason. If you feel you are being stopped unlawfully, it is within your rights to capture video of the encounter.",
  "Am I legally required to get out of the car if an officer tells me to?",
  "The police may ask you to get out of your vehicle (to ensure you don’t have a concealed weapon), but you do have the right to remain in your vehicle. Practically speaking, it may be a good idea to comply if they make this request to avoid escalation; but it varies by situation. You also have the right to remain silent, although it can be good idea to answer simple questions (e.g., “Do you know why I pulled you over?”) or make polite small talk (e.g., “Good morning officer.”).",
  "If you are a passenger, you have the right to ask if you can leave. If the officer agrees, then you may leave. ",
  "May the police search my car?",
  "Even if the reason for the stop is something minor, they may look around for signs of illegal activity or contraband as long as it’s in “plain view.” If the officers have reason to believe they are in imminent danger or they see evidence of a possible crime (such as blood splatter on the carseat), they may search the car. ",
  "If they ask you to open your trunk or glove compartment, however, you may decline unless they have a valid search warrant. That said, they may search your glove compartment if they have reason to believe you are concealing a weapon. If you consent to a search, then you have waived your rights. If you do not consent to a search and they search your vehicle anyway, any evidence they find may not be used against you. ",
  "What happens if I am arrested?",
  "The police may read you your Miranda rights once they arrest you, but it’s not necessary for them to do so right away. Even if the officer delays your Miranda warning, you still have the right to remain silent. ",
  "Your Miranda rights (rights of suspects upon lawful arrest) specifically include the following:",
  "The right to remain silent. You’re not obligated to answer questions about where you are going or traveling from; what you are doing; where you live; or where you were born, whether you are a U.S. citizen, or how you entered the country. If you want to exercise this right, simply say so. ",
  "The right to a government-appointed lawyer. You have the right to seek legal representation and must be given the opportunity to call a lawyer after your arrest. If you can’t afford an attorney, you may be appointed a public defender. The police may not listen to the phone call with your lawyer, but they may listen to phone calls with other parties.",
  "When you’re arrested, the arresting officer will put you in handcuffs and search you on the spot. Then, they’ll likely place you in a patrol car or, if they’re on foot, call for backup. Once you’re transported to a local jail, you will be processed (identified, fingerprinted, photographed, and issued one or more citations). The citation will indicate a specific charge or charges and the date on which you’re expected to appear in court.",
  "You may be in police custody for at least several hours, but you could be held in jail overnight or even over the weekend (before bail is set). However, you also may be released on your own recognizance—meaning that you’ve signed a promise to appear at your court hearing—or simply released without charges. ",
  "What if I’m illegally detained?",
  "If you are illegally detained (meaning they have arrested you without probable cause), then you probably will want to file a police misconduct claim or contact a civil rights legal defense organization once it’s safe to do so. Until then, it is typically in your best interest not to argue or resist—even if you believe the arrest is unlawful—since it could lead to an escalation and result in a dangerous situation or, at minimum, additional charges.",
  "Also, even if it was done without probable cause, resisting an illegal arrest could provide a measure of cover for the officer and make it more difficult for you to assert your rights later. Remember, it often comes down to your word versus that of the officer (although eyewitness video or a police body cam could be helpful in these scenarios).",
];

List<int> drivingAmount = [
  0,
  3,
  7,
  11,
  16,
  19,
  26,
];
